version: '3.8'

services:
  app:
    build: .
    container_name: jira_app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://db:5432/jira
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    expose:
      - "8080"
    networks:
      - backend

  db:
    image: postgres:15
    container_name: jira_db
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: jira_nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
